apiVersion: v1
kind: Service
metadata:
  labels:
    name: testkafkapublisherservice
  name: testkafkapublisherservice
spec:
  selector:
    app: test-topic-publisher
  type: NodePort
  ports:
  - port: 8097
    targetPort: 8096
