apiVersion: v1
kind: Service
metadata:
  labels:
    name: testkafkapublisherservice
  name: testkafkapublisherservice
spec:
  ports:
  - port: 8097
    targetPort: 8096
  selector:
    app: test-topic-publisher-ms
  type: NodePort
